### ISSUE TITLE
Make Camera View smoother

### ISSUE THREAD

**Issue by wendyho** [team-law/team-project#55]
Have a vertical and horizontal view
Fix UI for take picture and upload picture to be similar to snapchat
Fix ratio for ivPreviewImage

**Comment by geruk** [comment]
Filtering: vintage (?), text (?), 
UI Effect when taking picture.
Effect when taking picture: allowed number decreased (?), upload (?),

**Comment by pjrodz4** [comment]
Added seflie mode. 
Crashes unexpectedly.
